
multilingual: false
minimal: false
default_lang: ca

## Normally used in the footer
# project_info:
#   name: "Projecte TRAMVIDA"
#   contact_email: "tramvida@urv.cat"
#   website: "https://tramvida.urv.cat"
#   funding: "Projecte finançat pel Departament de Recerca i Universitats de la Generalitat de Catalunya"
#   logos:
#     - path: "/assets/images/logos/dgeo-bandera-color.png"
#       alt: "Departament de Geografia"
#     - path: "/assets/images/logos/logo-gratet.jpg"
#       alt: "GRATET"

style:
  green: "#2ea44f"
  green_hover: "#238636"
  black: "#222222"
  white: "#ffffff"
  link: "#0077cc"
  lang_active: "#2ea44f"
  hero_text: "#ffffff"

# template:
#  name: "GRATETemplates"
#  maintainer: "Grup de Recerca en Anàlisi Territorial i Estudis Turístics (GRATET)"
#  url: "https://gratet.urv.cat"

#google_site_verification: "abc123XYZ_your_code_here"

include:
  - contents

defaults:
  - scope:
      path: "contents/ca"
    values:
      permalink: "/ca/"
      lang: ca
      layout: default
  - scope:
      path: "contents/es"
    values:
      permalink: "/es/"
      lang: es
      layout: default
  - scope:
      path: "contents/en"
    values:
      permalink: "/en/"
      lang: en
      layout: default
